# Generated by Django 4.2.11 on 2024-03-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_1',
            name='candy_or_cookie',
            field=models.CharField(choices=[('0', '糖果'), ('1', '餅乾')], default='0', max_length=1),
        ),
    ]
