# Generated by Django 5.2.8 on 2025-11-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_tb_1_options_tb_1__time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('score_a', models.FloatField(default=0.25)),
                ('score_b', models.FloatField(default=0.25)),
                ('score_c', models.FloatField(default=0.25)),
                ('score_d', models.FloatField(default=0.25)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tb_1',
            options={'ordering': ['-_time'], 'verbose_name': '用戶資料庫'},
        ),
    ]
