# Generated by Django 5.2.8 on 2025-11-06 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_weightconfiguration_alter_tb_1_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb_1',
            options={'ordering': ['-_time'], 'verbose_name': '用戶資料庫', 'verbose_name_plural': '用戶資料庫'},
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('value_a', models.FloatField(default=0)),
                ('value_b', models.FloatField(default=0)),
                ('value_c', models.FloatField(default=0)),
                ('value_d', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weight_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.weightconfiguration')),
            ],
        ),
    ]
