# Generated by Django 5.2.8 on 2025-11-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_tb_1_options_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPriorityConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('field_order', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '欄位優先順序配置',
            },
        ),
    ]
