# Generated by Django 5.2.8 on 2025-11-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_fieldpriorityconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(help_text='用戶標識', max_length=64)),
                ('sentence', models.TextField(help_text='語句內容')),
                ('category', models.CharField(blank=True, help_text='分類', max_length=64)),
                ('embedding', models.JSONField(blank=True, default=list, help_text='語意向量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '語句資料庫',
            },
        ),
    ]
