# Generated by Django 5.2.8 on 2025-11-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_sentencedatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTPromptConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('classification', '分類'), ('generation', '生成'), ('summarization', '摘要'), ('custom', '自訂')], default='custom', max_length=32)),
                ('prompt', models.TextField(help_text='提示詞內容')),
                ('model', models.CharField(default='gpt-3.5-turbo', help_text='模型名稱', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '語句資料庫',
            },
        ),
        migrations.AlterModelOptions(
            name='sentencedatabase',
            options={},
        ),
    ]
