# Generated by Django 5.2.8 on 2025-11-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_gptpromptconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncPathConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='同步路徑', max_length=256, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '雲端同步路徑配置',
            },
        ),
        migrations.AlterModelOptions(
            name='gptpromptconfiguration',
            options={'verbose_name_plural': 'GPT提示詞配置'},
        ),
        migrations.AlterModelOptions(
            name='sentencedatabase',
            options={'verbose_name_plural': '語句資料庫'},
        ),
    ]
