# Generated by Django 5.2.8 on 2025-11-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_syncpathconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncpathconfiguration',
            name='name',
            field=models.CharField(blank=True, help_text='路徑名稱', max_length=100, null=True, unique=True),
        ),
    ]
