# Generated by Django 5.2.8 on 2025-11-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_syncpathconfiguration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncpathconfiguration',
            name='name',
            field=models.CharField(default=3, help_text='路徑名稱', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
