# Generated by Django 5.2.8 on 2025-11-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_syncpathconfiguration_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.CharField(help_text='會話ID', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='會話標題', max_length=200)),
                ('messages', models.JSONField(default=list, help_text='對話訊息陣列')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '聊天會話',
            },
        ),
    ]
