# Generated by Django 5.2.8 on 2025-11-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_chatsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_item', models.CharField(help_text='配置項名稱', max_length=200)),
                ('category', models.CharField(help_text='AI生成的分類名稱', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'AI分類記憶',
                'unique_together': {('configuration_item', 'category')},
            },
        ),
    ]
