# Generated by Django 5.2.8 on 2025-11-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_categorymemory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='原始檔案名稱', max_length=255)),
                ('stored_filename', models.CharField(help_text='儲存檔案名稱', max_length=255)),
                ('upload_time', models.DateTimeField(auto_now_add=True, help_text='上傳時間')),
                ('file_size', models.IntegerField(help_text='檔案大小(bytes)')),
                ('file_path', models.CharField(default='uploads/', help_text='檔案儲存路徑', max_length=255)),
            ],
            options={
                'verbose_name_plural': '上傳檔案記錄',
            },
        ),
    ]
