# Generated by Django 5.2.8 on 2025-11-06 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='使用者名稱', max_length=64, unique=True)),
                ('email', models.EmailField(help_text='電子郵件', max_length=128, unique=True)),
                ('password', models.CharField(help_text='密碼 hash', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
            ],
            options={
                'verbose_name_plural': '使用者',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='商品名稱', max_length=128)),
                ('amount', models.IntegerField(help_text='數量')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', help_text='訂單狀態', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='訂單建立時間')),
                ('user', models.ForeignKey(help_text='下單者', on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
            ],
            options={
                'verbose_name_plural': '訂單',
                'ordering': ['-created_at'],
            },
        ),
    ]
